# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a4ac5da9f273e795c07ce8c44e3d68c8"
name = "Announcement Bar"
handle = "announcement-bar-78"
application_url = "https://logistics-rx-noted-accomplish.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-d334c3af.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://logistics-rx-noted-accomplish.trycloudflare.com/auth/callback",
  "https://logistics-rx-noted-accomplish.trycloudflare.com/auth/shopify/callback",
  "https://logistics-rx-noted-accomplish.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
